version: '3.8'

services:
  clinic-app:
    build: .
    container_name: clinic-live-streaming
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./public/hls:/app/public/hls
      - /var/www/html/hls:/var/www/html/hls
    environment:
      - NODE_ENV=production
    networks:
      - clinic-network

  nginx:
    image: tiangolo/nginx-rtmp
    container_name: clinic-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/www/html/hls:/var/www/html/hls
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - clinic-app
    networks:
      - clinic-network

networks:
  clinic-network:
    driver: bridge

volumes:
  hls-data: