name: HongNhanaction

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hongnhanpush
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/clinicRepo
            git fetch origin
            git checkout production
            git pull origin production
            npm install
            npm run build
            pm2 restart clinicRepoApp || pm2 start npm --name "clinicRepoApp" -- start
